steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/ai-real-image-classification/images/trainer:latest',
    '-f',
    'docker/trainer.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/ai-real-image-classification/images/trainer:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
